pay=int(input("Please enter basic pay: "))
hra=(0.1*pay)
print("HRA: ",hra)
ta=(0.05*pay)
print("TA: ",ta)
totalsal=(pay+hra+ta)
print("Total Salary is: ",totalsal)
tax=(totalsal*0.02)
print("Tax Deducted: ",tax)
payf=(totalsal-tax)
print("Salary Payable is: ",payf)