# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sLzrAvK7GukfKs7beMNWOeMHcpFeouX6
"""

from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import accuracy_score

data=load_iris()

x,y=data.data,data.target

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=54)

model=RandomForestClassifier(random_state=54)

param_grid={
    "n_estimators":[50,100,150],
    "max_depth":[3,5,10,None],
    "min_samples_split":[2,5,10],
    "max_features":["sqrt","log2"]
}

grid=GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(x_train,y_train)

best_model=grid.best_estimator_
preds=best_model.predict(x_test)

print("best params: ",grid.best_params_)
print("accuracy: ",accuracy_score(y_test,preds))

